services:
    dem:
      build:
        context: ./dem
        dockerfile: dockerfile
      volumes:
        - ./files:/dem/files
      ports:
        - 8081:8080
    
    mdm:
      build:
        context: ./mdm
        dockerfile: dockerfile
      depends_on:
        - dem
      ports:
        - 8082:8082